version: '2'
services:
  mysql:
    build: ./mysql
    environment:
      MYSQL_DATABASE: order
      MYSQL_ROOT_PASSWORD: pass
    ports:
            - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  php:
    build: ./php
    ports:
      - '9000:80'
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mysql
volumes:
  db:
